// Here Be Dragons DS — scripts/build-tokens.js
// Reads tokens/tokens.json (W3C DTCG format) → writes tokens/tokens.css
// Run: node scripts/build-tokens.js

const fs   = require('fs');
const path = require('path');

const ROOT       = path.resolve(__dirname, '..');
const TOKEN_JSON = path.join(ROOT, 'tokens', 'tokens.json');
const TOKEN_CSS  = path.join(ROOT, 'tokens', 'tokens.css');

// Organisational tier keys: stripped when building CSS var names.
// e.g. color.primitive.ink-900 → --hbd-color-ink-900
const SKIP_SEGMENTS = new Set(['primitive', 'semantic', 'component']);

// Category name aliases (top-level key remapping)
const CATEGORY_MAP = { spacing: 'space' };

function toCssVarName(segments) {
  const parts = segments
    .map((s, i) => {
      if (SKIP_SEGMENTS.has(s)) return null;
      if (i === 0 && CATEGORY_MAP[s]) return CATEGORY_MAP[s];
      return s;
    })
    .filter(Boolean);
  return `--hbd-${parts.join('-')}`;
}

// Recursively collect leaf tokens from the W3C DTCG tree
function collectTokens(node, segments = []) {
  const tokens = [];
  for (const [key, val] of Object.entries(node)) {
    if (key.startsWith('$')) continue;
    if (val && typeof val === 'object' && '$value' in val) {
      tokens.push({ segments: [...segments, key], value: val.$value, type: val.$type });
    } else if (val && typeof val === 'object') {
      tokens.push(...collectTokens(val, [...segments, key]));
    }
  }
  return tokens;
}

// Walk a dotted path like "color.primitive.ink-900" through the raw JSON tree
function lookupByDotPath(tree, dotPath) {
  return dotPath.split('.').reduce((node, key) => (node && typeof node === 'object' ? node[key] : null), tree);
}

const ALIAS_RE = /^\{([^}]+)\}$/;

// Resolve a token value: if it is an alias ({a.b.c}), return the CSS var() reference.
// Does NOT recursively chase alias chains — they are resolved at CSS runtime via the cascade.
function resolveValue(value) {
  const match = ALIAS_RE.exec(value);
  if (!match) return { css: String(value), isAlias: false };
  const dotPath  = match[1];
  const segments = dotPath.split('.');
  const cssVar   = toCssVarName(segments);
  return { css: `var(${cssVar})`, isAlias: true };
}

// Validate the token file exists
if (!fs.existsSync(TOKEN_JSON)) {
  console.error(`Error: ${TOKEN_JSON} not found. Create tokens/tokens.json first.`);
  process.exit(1);
}

const tree = JSON.parse(fs.readFileSync(TOKEN_JSON, 'utf8'));

// Collect tokens grouped by top-level key so we can emit section comments
function collectGroups(obj) {
  const groups = [];
  for (const [topKey, topVal] of Object.entries(obj)) {
    if (topKey.startsWith('$')) continue;
    const tokens = [];
    if (topVal && typeof topVal === 'object' && '$value' in topVal) {
      tokens.push({ segments: [topKey], value: topVal.$value, type: topVal.$type });
    } else if (topVal && typeof topVal === 'object') {
      tokens.push(...collectTokens(topVal, [topKey]));
    }
    if (tokens.length > 0) groups.push({ key: topKey, tokens });
  }
  return groups;
}

const groups = collectGroups(tree);
let tokensWritten   = 0;
let aliasesResolved = 0;

const lines = [':root {'];
for (let gi = 0; gi < groups.length; gi++) {
  const { key, tokens } = groups[gi];
  lines.push(`  /* ── ${key} ${'─'.repeat(Math.max(0, 52 - key.length))} */`);
  for (const token of tokens) {
    const cssVar        = toCssVarName(token.segments);
    const { css, isAlias } = resolveValue(token.value);
    if (isAlias) aliasesResolved++;
    lines.push(`  ${cssVar}: ${css};`);
    tokensWritten++;
  }
  if (gi < groups.length - 1) lines.push('');
}
lines.push('}');

const output = [
  `/* Here Be Dragons DS — tokens/tokens.css`,
  ` * Generated by scripts/build-tokens.js — do not edit by hand.`,
  ` * Source of truth: tokens/tokens.json`,
  ` */`,
  '',
  lines.join('\n'),
  '',
].join('\n');

fs.writeFileSync(TOKEN_CSS, output);
console.log(`tokens.css written — ${tokensWritten} tokens written, ${aliasesResolved} aliases resolved.`);
